server:
    port: ${SERVER_PORT:8080}

spring:
    application:
        name: ${APPLICATION_NAME:bookstore}
    datasource:
        url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:bookstore}
        username: ${DATABASE_USERNAME:root}
        password: ${DATABASE_PASSWORD:root}
    jpa:
        show-sql: ${JPA_SHOW_SQL:false}
        properties:
            hibernate:
                format_sql: ${HIBERNATE_FORMAT_SQL:false}
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            max-file-size: 500MB
            max-request-size: 500MB

com:
    learn:
        cloudinary:
            name: ${CLOUDINARY_NAME:duhumawiq}
            api:
                key: ${CLOUDINARY_API_KEY:119948159122814}
                secret: ${CLOUDINARY_API_SECRET:dVF_AkcNk985SqZQcDBYErDHDZI}
                
logging:
    level:
        org:
            springframework:
                security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}
    pattern:
        console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
